extends Node
"""
CREATE A SPAWN MANAGER FOR ENEMIES LIKE LIMIT SPAWN TO 20?
ADD TIMER FOR SPAWNING AND ADD SPAWN POINTS ON THE MAP

CREATE A SPAWN POINT FOR PLAYER [CHECKPOINT]

CREATE SPAWN POINT FOR THE KEYS IN THE 3RD QUEST

"""
